[package]
name = "huskyTech2"
version = "0.0.1"
edition = "2021"

[features]
default = [ "glfw" ]
glfw = []

[dependencies]
gltf = { version = "1.0" }
gfx-maths = "0.2.8"
kira = "0.6.0"
png = "0.17.5"
log = "0.4.0"
env_logger = "0.8.4"

[target.'cfg(target_os = "linux")'.dependencies]
libsex = { path = "../libsex" }