[package]
name = "huskyTech2"
version = "0.0.1"
edition = "2021"

[features]
default = [ "glfw" ]
glfw = []

[dependencies]
dae-parser = "0.8.7"
gfx-maths = "0.2.8"

[target.'cfg(target_os = "linux")'.dependencies]
libsex = { path = "../libsex" }