[package]
name = "huskyTech2"
version = "0.0.1"
edition = "2021"

[features]
default = [ "glfw" ]
glfw = []

[dependencies]
gltf = { version = "1.0" }
serde = { version = "1.0", features = ["derive"] }
gfx-maths = { version = "0.2.8", features = ["serde"]}
tokio = { version = "1", features = ["full"] }
uuid = { version = "1.1.2", features = ["v4"] }
async-recursion = "1.0.0"
physx-sys = "0.5.0"
rmp-serde = "1.1.0"
kira = "0.6.0"
image = "0.24.3"
log = "0.4.0"
env_logger = "0.8.4"
gl_matrix = "0.0"
lazy_static = "1.4.0"

[target.'cfg(target_os = "linux")'.dependencies]
libsex = { path = "../libsex" }